name: Stargazers Count

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */5 * * *'
  watch:
    types: [started]

jobs:
  update-stargazers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update stargazers count
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          import requests
          import json
          import os

          def get_stargazers(repo):
              url = f'https://api.github.com/repos/{repo}/stargazers'
              headers = {'Authorization': f'token {os.getenv("GITHUB_TOKEN")}'}
              stargazers = set()
              page = 1

              while True:
                  response = requests.get(url, headers=headers, params={'page': page, 'per_page': 100})
                  if response.status_code != 200:
                      break
                  data = response.json()
                  if not data:
                      break
                  stargazers.update(user['login'] for user in data)
                  page += 1

              return stargazers

          def format_count(count):
              if count < 1000:
                  return str(count)
              return f'{count / 1000:.1f}K'.rstrip('0').rstrip('.')

          repo1 = 'icon11-community/Folder11-Ico'
          repo2 = 'icon11-community/Folder11'

          stargazers1 = get_stargazers(repo1)
          stargazers2 = get_stargazers(repo2)

          unique_stargazers = stargazers1.union(stargazers2)
          total_unique_stargazers = len(unique_stargazers)

          stargazers_count = format_count(total_unique_stargazers)

          only_repo1 = len(stargazers1 - stargazers2)
          only_repo2 = len(stargazers2 - stargazers1)
          both_repos = len(stargazers1.intersection(stargazers2))

          percentage_repo1 = (only_repo1 / total_unique_stargazers) * 100
          percentage_repo2 = (only_repo2 / total_unique_stargazers) * 100
          percentage_both = (both_repos / total_unique_stargazers) * 100

          json_file = 'Folder11-Ico/folder11.json'
          data = {
              "stargazers": stargazers_count,
              "percentages": {
                  "Folder11-Ico_only": f"{percentage_repo1:.1f}%",
                  "Folder11_only": f"{percentage_repo2:.1f}%",
                  "both": f"{percentage_both:.1f}%"
              }
          }

          with open(json_file, 'w') as f:
              json.dump(data, f, indent=4)

          print(f'Updated {json_file} with stargazers count and percentages')

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Folder11-Ico/folder11.json
          git commit -m 'Update stargazers count and percentages'
          git push
